# This action use https://github.com/wow-actions/add-badges?tab=readme-ov-file to add badges to your README.md file.
# this update the reame state every hour
name: Check Badges

# on:
#   schedule:
#     - cron: "0 1-23 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/add-badges@v1
        env:
          repo_url: ${{ github.event.repository.html_url }}
          repo_name: ${{ github.event.repository.name }}
          repo_owner: ${{ github.event.repository.owner.login }}
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          badges: |
            [
              {
                "badge": "https://img.shields.io/npm/v/${{ env.repo_name }}?style=flat-square",
                "alt": "NPM Version",
                "link": "https://www.npmjs.com/package/${{ env.repo_name }}"
              },
              {
                "badge": "https://img.shields.io/badge/language-TypeScript-blue.svg?style=flat-square",
                "alt": "Language",
                "link": "https://www.typescriptlang.org"
              }
            ]
